trigger:
  tags:
    include:
      - '*.*.*'

pr: none

jobs:

- job: release
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: |
        python -m pip install --upgrade pip setuptools wheel twine sphinx recommonmark
      displayName: 'Install requirements'

    - script: 'pip install twine'

    - script: cd doc && make htmlhelp && cd ..
      displayName: 'Build docs'
      continueOnError: false

    - script: python setup.py sdist bdist_wheel
      displayName: 'Build dist distribution files'
      continueOnError: false

    - task: CopyFiles@2
      condition: eq(variables['Agent.JobStatus'], 'Succeeded')
      inputs:
        contents: dist/**
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      condition: eq(variables['Agent.JobStatus'], 'Succeeded')
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
