trigger:
- master

jobs:

# Run tests on Linux
- template: .azure-pipelines/test_job.yml
  parameters:
    platform: linux
    orange_version: stable

- template: .azure-pipelines/test_job.yml
  parameters:
    platform: linux
    orange_version: development

# Run tests on macOS
- template: .azure-pipelines/test_job.yml
  parameters:
    platform: mac
    orange_version: stable

- template: .azure-pipelines/test_job.yml
  parameters:
    platform: mac
    orange_version: development

# Run tests on Windows
- template: .azure-pipelines/test_job.yml
  parameters:
    platform: windows
    orange_version: stable

- template: .azure-pipelines/test_job.yml
  parameters:
    platform: windows
    orange_version: development

- template: .azure-pipelines/lint_job.yml
